load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "gm-git",
    srcs = ["gm-git.cc"],
    copts = [
        "-std=c++17",
    ],
    linkopts = [
        "-std=c++17",
    ],
    deps = [
        "@abseil-cpp//absl/strings",
    ],
)
